"use strict";

const $ = (id) => document.getElementById(id);
const uid = (prefix) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const clone = (value) => JSON.parse(JSON.stringify(value));
const esc = (value="") => String(value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const int = (value) => Math.max(0, Math.floor(Number(value) || 0));

const DEFAULT_ECHELONS = [
  ["team","組（チーム）","Ø",1,false],["squad","分隊","●",2,false],["section","班（セクション）","●●",3,false],
  ["platoon","小隊","●●●",4,false],["company","中隊","|",5,false],["battalion","大隊","||",6,false],
  ["regiment","連隊","|||",7,false],["brigade","旅団","X",8,true],["division","師団","XX",9,true],
  ["corps","軍団","XXX",10,true],["army","軍","XXXX",11,true],["army-group","軍集団","XXXXX",12,true]
].map(([id,name,symbol,rank,brigadeOrAbove])=>({id,name,symbol,rank,brigadeOrAbove}));

const DEFAULT_TYPES = [
  ["infantry","歩兵"],["mech-inf","機械化歩兵"],["armor","機甲（戦車）"],["recon","偵察"],["artillery","砲兵"],
  ["sp-artillery","自走砲兵"],["mortar","迫撃砲"],["air-defense","防空"],["anti-tank","対戦車"],["engineer","工兵"],
  ["signal","通信"],["logistics","補給／兵站"],["medical","衛生"],["aviation","航空"],["hq","司令部"]
].map(([id,name])=>({id,name}));

const BROAD_CATEGORIES=["レーダー・センサー","防空・ミサイル防衛","火砲・ロケット砲","地上発射ミサイル","戦車・機動砲","装甲戦闘車両","工兵・支援車両","水上戦闘艦艇","航空母艦","揚陸・輸送艦艇","潜水艦・水中無人機","補助艦艇","固定翼航空機","回転翼航空機","無人航空機","その他"];
function broadCategory(type){if(/レーダー/.test(type))return"レーダー・センサー";if(/防空|対空|C-RAM|弾道ミサイル防衛/.test(type))return"防空・ミサイル防衛";if(/自走砲|火砲|砲兵|迫撃砲|ロケット砲|列車砲|要塞砲|沿岸砲|火炎放射/.test(type))return"火砲・ロケット砲";if(/主力戦車|軽戦車|機動砲|対戦車砲/.test(type))return"戦車・機動砲";if(/工兵|NBC|指揮・観測/.test(type))return"工兵・支援車両";if(/装甲|歩兵戦闘車|偵察車|対戦車ミサイル車両/.test(type))return"装甲戦闘車両";if(/地対地|地対艦|NLOSミサイル/.test(type))return"地上発射ミサイル";if(/潜水艦救難艦|潜水母艦|掃海母艦/.test(type))return"補助艦艇";if(/潜水艦|潜航|UUV|水中無人/.test(type))return"潜水艦・水中無人機";if(/航空母艦|空母/.test(type))return"航空母艦";if(/揚陸|上陸|輸送艦|輸送艇|遠征|エアクッション/.test(type))return"揚陸・輸送艦艇";if(/補給|掃海|敷設|観測艦|情報収集艦|測定艦|追跡艦|救難艦|母艦|砕氷船|油槽船|運搬艦/.test(type))return"補助艦艇";if(/フリゲート|コルベット|艦|艇|USV|船/.test(type))return"水上戦闘艦艇";if(/無人.*機|無人航空機/.test(type))return"無人航空機";if(/ヘリ/.test(type))return"回転翼航空機";if(/戦闘機|攻撃機|爆撃機|輸送機|哨戒機|偵察機|観測機|給油機|電子戦|SEAD|指揮機|早期警戒.*機|ガンシップ|地面効果翼機|練習機/.test(type))return"固定翼航空機";return"その他"}
const BASE_CATALOG = [{id:"eq-hifv40",name:"HIFV-40",category:"装甲戦闘車両",specs:"原種別: 重装甲歩兵戦闘車",sourceType:"重装甲歩兵戦闘車",notes:"旧世界固有兵器"}];
const IMPORTED_CATALOG = (window.ORBAT_CATALOG_DATA||[]).map(([name,sourceType,country],i)=>({
  id:`catalog-${String(i+1).padStart(4,"0")}`,name,category:broadCategory(sourceType),sourceType,
  specs:[country?`生産国: ${country}`:"",sourceType?`原種別: ${sourceType}`:""].filter(Boolean).join(" / "),notes:"兵器価格一覧(1).csvから価格を除外して収録"
}));
const CATALOG_SEED = [...BASE_CATALOG,...IMPORTED_CATALOG];
const DEFAULT_CATEGORIES = clone(BROAD_CATEGORIES);
const catalogKey = x => `${x.name}\u0000${x.category}\u0000${x.specs||""}`;
const SAMPLE_TANK=IMPORTED_CATALOG.find(x=>x.name==="M1A2"&&x.sourceType==="主力戦車")||IMPORTED_CATALOG.find(x=>x.sourceType==="主力戦車");
function mergeBuiltInCatalog(project){const obsolete=new Set(["eq-mbt","eq-rifle"]);for(const u of project.units||[]){const merged=new Map();for(const a of u.equipment||[]){let id=a.catalogId;if(id==="eq-mbt")id=SAMPLE_TANK.id;if(obsolete.has(id))continue;merged.set(id,(merged.get(id)||0)+int(a.quantity))}u.equipment=[...merged].map(([catalogId,quantity])=>({catalogId,quantity}))}project.catalog=project.catalog.filter(x=>!obsolete.has(x.id));const byId=new Map(project.catalog.map(x=>[x.id,x])),keys=new Set(project.catalog.map(catalogKey)),ids=new Set(project.catalog.map(x=>x.id));let added=0;for(const item of CATALOG_SEED){const current=byId.get(item.id);if(current){Object.assign(current,clone(item));continue}if(keys.has(catalogKey(item)))continue;const copy=clone(item);if(ids.has(copy.id))copy.id=uid("catalog");project.catalog.push(copy);keys.add(catalogKey(copy));ids.add(copy.id);added++}project.categories=[...new Set([...DEFAULT_CATEGORIES,...project.catalog.map(x=>x.category)])];return added}

const sampleProject = () => ({
  meta:{name:"サンプル編成",version:1,updatedAt:new Date().toISOString()},
  echelons:clone(DEFAULT_ECHELONS), unitTypes:clone(DEFAULT_TYPES),
  categories:clone(DEFAULT_CATEGORIES),
  catalog:clone(CATALOG_SEED),
  operations:[],
  units:[
    {id:"u-div",name:"第1機甲師団",abbr:"1AD",parentId:null,echelonId:"division",unitTypeId:"armor",affiliation:"friendly",sortOrder:1,personnel:null,equipment:[],notes:""},
    {id:"u-bde",name:"第1機甲旅団",abbr:"1AB",parentId:"u-div",echelonId:"brigade",unitTypeId:"armor",affiliation:"friendly",sortOrder:1,personnel:null,equipment:[],notes:""},
    {id:"u-tk1",name:"第1戦車大隊",abbr:"1Tk",parentId:"u-bde",echelonId:"battalion",unitTypeId:"armor",affiliation:"friendly",sortOrder:1,personnel:500,equipment:[{catalogId:SAMPLE_TANK.id,quantity:44}],notes:""},
    {id:"u-tk2",name:"第2戦車大隊",abbr:"2Tk",parentId:"u-bde",echelonId:"battalion",unitTypeId:"armor",affiliation:"friendly",sortOrder:2,personnel:500,equipment:[{catalogId:SAMPLE_TANK.id,quantity:44}],notes:""},
    {id:"u-mech",name:"第1機械化歩兵大隊",abbr:"1Mech",parentId:"u-bde",echelonId:"battalion",unitTypeId:"mech-inf",affiliation:"friendly",sortOrder:3,personnel:700,equipment:[{catalogId:"eq-hifv40",quantity:40}],notes:""}
  ]
});

let state = sampleProject();
let selectedId = "u-bde";
let collapsed = new Set();
let history = [], future = [], dirty = false;
let chartZoom = 1, chartPan = {x:40,y:40}, panStart = null;
let selectedOperationId = null, operationPane = "brief", mapDraftPoints = [], mapZoom = 1;

function echelon(id){ return state.echelons.find(x=>x.id===id) || state.echelons[0]; }
function unitType(id){ return state.unitTypes.find(x=>x.id===id) || {id:"",name:"未設定"}; }
function catalogItem(id){ return state.catalog.find(x=>x.id===id); }
function unit(id){ return state.units.find(x=>x.id===id); }
function children(id){ return state.units.filter(x=>x.parentId===id).sort((a,b)=>a.sortOrder-b.sortOrder || a.name.localeCompare(b.name,"ja")); }
function isAggregateOnly(u){ return !!echelon(u.echelonId).brigadeOrAbove; }
function descendants(id){ const out=[]; const walk=x=>children(x).forEach(c=>{out.push(c);walk(c.id)}); walk(id); return out; }
function aggregate(id, seen=new Set()){
  if(seen.has(id)) return {personnel:0,equipment:{}};
  seen.add(id); const u=unit(id); if(!u) return {personnel:0,equipment:{}};
  const result={personnel:isAggregateOnly(u)?0:int(u.personnel),equipment:{}};
  if(!isAggregateOnly(u)) (u.equipment||[]).forEach(a=>result.equipment[a.catalogId]=(result.equipment[a.catalogId]||0)+int(a.quantity));
  children(id).forEach(c=>{const sub=aggregate(c.id,seen);result.personnel+=sub.personnel;Object.entries(sub.equipment).forEach(([k,v])=>result.equipment[k]=(result.equipment[k]||0)+v)});
  return result;
}
function validateProject(data){
  if(!data || typeof data!=="object" || !Array.isArray(data.units)||!Array.isArray(data.catalog)||!Array.isArray(data.echelons)||!Array.isArray(data.unitTypes)) throw new Error("ORBATプロジェクトとして必要な配列がありません。");
  const ids=new Set(); for(const u of data.units){if(!u.id||ids.has(u.id)) throw new Error("部隊IDが不正または重複しています。");ids.add(u.id)}
  for(const u of data.units){let cur=u,seen=new Set([u.id]);while(cur.parentId){if(seen.has(cur.parentId))throw new Error(`循環参照を検出: ${u.name}`);seen.add(cur.parentId);cur=data.units.find(x=>x.id===cur.parentId);if(!cur)break}}
  return true;
}
function checkpoint(){ history.push(JSON.stringify(state)); if(history.length>60)history.shift(); future=[]; dirty=true; state.meta.updatedAt=new Date().toISOString(); updateHeader(); }
function mutate(fn){ checkpoint(); fn(); renderAll(); }
function undo(){if(!history.length)return;future.push(JSON.stringify(state));state=JSON.parse(history.pop());selectedId=unit(selectedId)?selectedId:state.units[0]?.id;dirty=true;renderAll()}
function redo(){if(!future.length)return;history.push(JSON.stringify(state));state=JSON.parse(future.pop());selectedId=unit(selectedId)?selectedId:state.units[0]?.id;dirty=true;renderAll()}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
function download(name,blob){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function isDark(){return true}

function renderAll(){ updateHeader(); renderTree(); renderDetail(); renderCatalog(); renderSettings(); renderOperations(); populateChartRoots(); if($("chartView").classList.contains("active")) renderChart(); }
function updateHeader(){ $("projectName").textContent=state.meta.name+(dirty?" • 未保存":"");$("undoBtn").disabled=!history.length;$("redoBtn").disabled=!future.length; }
function switchView(name){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view-btn").forEach(x=>x.classList.toggle("active",x.dataset.view===name));$(`${name}View`).classList.add("active");if(name==="chart")renderChart();if(name==="operations")renderOperations()}

function renderTree(){
  const q=$("treeSearch").value.trim().toLowerCase(); const roots=children(null);
  const matches=u=>!q || u.name.toLowerCase().includes(q)||(u.abbr||"").toLowerCase().includes(q)||descendants(u.id).some(matches);
  const row=(u,depth)=>{if(!matches(u))return"";const kids=children(u.id),open=q||!collapsed.has(u.id);return `<div class="tree-row ${u.id===selectedId?"selected":""}" style="padding-left:${depth*15}px" role="treeitem"><button class="tree-toggle" data-action="toggle" data-id="${u.id}" ${kids.length?"":"disabled"}>${kids.length?(open?"▾":"▸"):"·"}</button><span class="tree-symbol">${unitSymbolSvg(u,{width:30,height:22,labels:false,dark:isDark()})}</span><span class="tree-label" data-action="select" data-id="${u.id}">${esc(u.name)}<small>${esc(echelon(u.echelonId).name)} · ${esc(unitType(u.unitTypeId).name)}</small></span><span class="tree-actions"><button data-action="up" data-id="${u.id}" title="上へ">↑</button><button data-action="down" data-id="${u.id}" title="下へ">↓</button><button data-action="add" data-id="${u.id}" title="子部隊追加">＋</button></span></div>${open?kids.map(c=>row(c,depth+1)).join(""):""}`};
  $("unitTree").innerHTML=roots.length?roots.map(r=>row(r,0)).join(""):`<div class="empty-state"><p>部隊がありません。</p></div>`;
}
function selectOptions(items,value,label=x=>x.name){return items.map(x=>`<option value="${esc(x.id)}" ${x.id===value?"selected":""}>${esc(label(x))}</option>`).join("")}
function renderEquipmentPicker(){const filter=$("equipmentCategoryFilter").value,current=$("equipmentPicker").value,items=[...state.catalog].filter(x=>!filter||x.category===filter).sort((a,b)=>a.name.localeCompare(b.name,"ja")||a.specs.localeCompare(b.specs,"ja"));$("equipmentPicker").innerHTML=items.length?items.map(x=>`<option value="${esc(x.id)}" data-category="${esc(x.category)}">${esc(x.name)}${x.specs?` — ${esc(x.specs)}`:""}</option>`).join(""):`<option value="">該当する兵器がありません</option>`;if(items.some(x=>x.id===current))$("equipmentPicker").value=current}
function renderDetail(){
  const u=unit(selectedId); $("emptyDetail").hidden=!!u;$("detailContent").hidden=!u;
  if(!u){$("symbolPreview").innerHTML="<p>部隊を選択すると記号を表示します。</p>";return}
  $("detailTitle").textContent=u.name;$("unitName").value=u.name;$("unitAbbr").value=u.abbr||"";$("unitNotes").value=u.notes||"";
  $("unitEchelon").innerHTML=selectOptions([...state.echelons].sort((a,b)=>a.rank-b.rank),u.echelonId,x=>`${x.symbol} ${x.name}`);
  $("unitType").innerHTML=selectOptions(state.unitTypes,u.unitTypeId);$("unitAffiliation").value=u.affiliation;
  const forbidden=new Set(descendants(u.id).map(x=>x.id));forbidden.add(u.id);
  $("unitParent").innerHTML=`<option value="">（ルート）</option>`+selectOptions(state.units.filter(x=>!forbidden.has(x.id)),u.parentId||"",x=>`${x.name}［${echelon(x.echelonId).name}］`);
  const direct=!isAggregateOnly(u);$("directSection").hidden=!direct;
  $("unitPersonnel").value=direct?int(u.personnel):"";
  const currentFilter=$("equipmentCategoryFilter").value;$("equipmentCategoryFilter").innerHTML=`<option value="">全区分（${state.catalog.length.toLocaleString()}品目）</option>`+[...new Set(state.catalog.map(x=>x.category))].sort((a,b)=>a.localeCompare(b,"ja")).map(category=>`<option value="${esc(category)}">${esc(category)}（${state.catalog.filter(x=>x.category===category).length}）</option>`).join("");if([...$("equipmentCategoryFilter").options].some(x=>x.value===currentFilter))$("equipmentCategoryFilter").value=currentFilter;renderEquipmentPicker();
  renderEquipmentTables(u); const agg=aggregate(u.id);$("aggregatePersonnel").textContent=`人員 ${agg.personnel.toLocaleString()}名`;
  $("aggregateTitle").textContent=isAggregateOnly(u)?"配下全部隊の集計":"配下を含む総計";
  const categories={};Object.entries(agg.equipment).forEach(([id,qty])=>{const item=catalogItem(id);const c=item?.category||"不明";categories[c]=(categories[c]||0)+qty});
  $("categorySummary").innerHTML=Object.entries(categories).sort().map(([c,q])=>`<span class="stat"><strong>${esc(c)}</strong> ${q.toLocaleString()}</span>`).join("")||`<span class="stat">装備なし</span>`;
  $("symbolPreview").innerHTML=unitSymbolSvg(u,{width:250,height:180,labels:true,dark:isDark()});
  const warns=[];if(u.parentId){const p=unit(u.parentId);if(p&&echelon(u.echelonId).rank>=echelon(p.echelonId).rank)warns.push("子部隊の階梯が上級部隊と同格以上です。")}if(isAggregateOnly(u)&&((u.equipment||[]).length||u.personnel))warns.push("旅団以上の部隊に直接割当データがあります。JSON出力前に解消してください。");
  $("warningBox").hidden=!warns.length;$("warningBox").innerHTML=warns.map(esc).join("<br>");
}
function equipmentRows(entries,editable){
  const rows=Object.entries(entries).filter(([,q])=>q>0).sort((a,b)=>(catalogItem(a[0])?.category||"").localeCompare(catalogItem(b[0])?.category||"")||(catalogItem(a[0])?.name||"").localeCompare(catalogItem(b[0])?.name||""));
  if(!rows.length)return `<p class="muted">装備の割当はありません。</p>`;
  return `<table class="data-table"><thead><tr><th>区分</th><th>品目</th><th>数量</th>${editable?"<th></th>":""}</tr></thead><tbody>${rows.map(([id,qty])=>{const item=catalogItem(id)||{name:`不明 (${id})`,category:"不明"};return `<tr><td>${esc(item.category)}</td><td>${esc(item.name)}</td><td>${editable?`<input class="assignment-qty" data-id="${esc(id)}" type="number" min="0" value="${qty}">`:qty.toLocaleString()}</td>${editable?`<td><button class="danger assignment-delete" data-id="${esc(id)}">削除</button></td>`:""}</tr>`}).join("")}</tbody></table>`;
}
function renderEquipmentTables(u){const direct=Object.fromEntries((u.equipment||[]).map(a=>[a.catalogId,int(a.quantity)]));$("directEquipment").innerHTML=equipmentRows(direct,true);$("aggregateEquipment").innerHTML=equipmentRows(aggregate(u.id).equipment,false)}

function affiliationStyle(a){return {friendly:{stroke:"#225f87",fill:"#e9f5fb"},hostile:{stroke:"#a33b3b",fill:"#fff0f0"},neutral:{stroke:"#3c8a55",fill:"#eefaf1"},unknown:{stroke:"#8c6e21",fill:"#fff8e2"}}[a]||{stroke:"#333",fill:"#fff"}}
function glyph(type,x,y,w,h){
  const L=(x1,y1,x2,y2,extra="")=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" ${extra}/>`; const cx=x+w/2,cy=y+h/2;
  const oval=`<ellipse cx="${cx}" cy="${cy}" rx="${w*.27}" ry="${h*.25}"/>`, cross=L(x+w*.2,y+h*.2,x+w*.8,y+h*.8)+L(x+w*.8,y+h*.2,x+w*.2,y+h*.8);
  switch(type){case"infantry":return cross;case"mech-inf":return cross+oval;case"armor":return oval;case"recon":return L(x+w*.2,y+h*.8,x+w*.8,y+h*.2);case"artillery":return `<circle cx="${cx}" cy="${cy}" r="${h*.16}" fill="currentColor"/>`;case"sp-artillery":return `<circle cx="${cx}" cy="${cy-h*.1}" r="${h*.11}" fill="currentColor"/>`+oval;case"mortar":return `<circle cx="${cx}" cy="${cy+h*.13}" r="${h*.1}" fill="currentColor"/>`+L(cx,cy+h*.05,cx,y+h*.18)+`<polyline points="${cx-h*.1},${y+h*.3} ${cx},${y+h*.16} ${cx+h*.1},${y+h*.3}"/>`;case"air-defense":return `<path d="M ${x+w*.2} ${y+h*.72} Q ${cx} ${y+h*.12} ${x+w*.8} ${y+h*.72}"/>`;case"anti-tank":return `<polyline points="${x+w*.25},${y+h*.7} ${cx},${y+h*.25} ${x+w*.75},${y+h*.7}"/>`;case"engineer":return `<path d="M${x+w*.28} ${y+h*.2}V${y+h*.8}M${x+w*.28} ${y+h*.2}H${x+w*.72}M${x+w*.28} ${cy}H${x+w*.62}M${x+w*.28} ${y+h*.8}H${x+w*.72}"/>`;case"signal":return `<polyline points="${x+w*.3},${y+h*.75} ${cx},${y+h*.2} ${cx},${y+h*.7} ${x+w*.7},${y+h*.25}"/>`;case"medical":return L(cx,y+h*.22,cx,y+h*.78,"stroke-width=5")+L(x+w*.3,cy,x+w*.7,cy,"stroke-width=5");case"aviation":return `<path d="M${x+w*.2} ${cy}L${cx} ${y+h*.25}L${x+w*.8} ${cy}L${cx} ${y+h*.42}V${y+h*.75}"/>`;case"hq":return `<text x="${cx}" y="${cy+h*.12}" text-anchor="middle" font-size="${h*.35}" font-weight="700">HQ</text>`;case"logistics":return `<path d="M${x+w*.25} ${y+h*.32}H${x+w*.68}L${x+w*.78} ${cy}V${y+h*.67}H${x+w*.25}Z"/>`+`<circle cx="${x+w*.38}" cy="${y+h*.72}" r="${h*.07}"/><circle cx="${x+w*.66}" cy="${y+h*.72}" r="${h*.07}"/>`;default:return `<text x="${cx}" y="${cy+h*.15}" text-anchor="middle" font-size="${h*.32}">?</text>`}
}
// APP-6D / MIL-STD-2525D land-unit frame proportions. The friendly frame is 3:2.
// Diamond, square and quatrefoil frames use square bounds and must never be stretched.
const APP6D_FRAME_ASPECT={friendly:1.5,hostile:1,neutral:1,unknown:1};
function frameShape(a,x,y,w,h){if(a==="hostile")return `<polygon class="node-frame" points="${x+w/2},${y} ${x+w},${y+h/2} ${x+w/2},${y+h} ${x},${y+h/2}"/>`;if(a==="neutral")return `<rect class="node-frame" x="${x}" y="${y}" width="${w}" height="${h}"/>`;if(a==="unknown")return `<path class="node-frame" d="M${x+w*.5} ${y}Q${x+w*.75} ${y} ${x+w*.75} ${y+h*.25}Q${x+w} ${y+h*.25} ${x+w} ${y+h*.5}Q${x+w} ${y+h*.75} ${x+w*.75} ${y+h*.75}Q${x+w*.75} ${y+h} ${x+w*.5} ${y+h}Q${x+w*.25} ${y+h} ${x+w*.25} ${y+h*.75}Q${x} ${y+h*.75} ${x} ${y+h*.5}Q${x} ${y+h*.25} ${x+w*.25} ${y+h*.25}Q${x+w*.25} ${y} ${x+w*.5} ${y}Z"/>`;return `<rect class="node-frame" x="${x}" y="${y}" width="${w}" height="${h}"/>`}
function frameGeometry(a,width,height,labels){const aspect=APP6D_FRAME_ASPECT[a]||1.5,maxW=labels?Math.min(width*.62,120):width*.9,maxH=labels?Math.min(height*.42,72):height*.9;let h=Math.min(maxH,maxW/aspect),w=h*aspect;if(w>maxW){w=maxW;h=w/aspect}return{x:(width-w)/2,y:labels?Math.max(20,height*.18):Math.max(1,(height-h)/2),w,h}}
function iconGeometry(a,f){if(a==="hostile")return{x:f.x+f.w*.22,y:f.y+f.h*.22,w:f.w*.56,h:f.h*.56};if(a==="unknown")return{x:f.x+f.w*.18,y:f.y+f.h*.18,w:f.w*.64,h:f.h*.64};return{x:f.x+f.w*.08,y:f.y+f.h*.08,w:f.w*.84,h:f.h*.84}}
function unitSymbolSvg(u,opt={}){const width=opt.width||180,height=opt.height||130,labels=opt.labels!==false,f=frameGeometry(u.affiliation,width,height,labels),g=iconGeometry(u.affiliation,f),st=affiliationStyle(u.affiliation),ec=echelon(u.echelonId),label=opt.dark?"#dce6ef":"#172233",muted=opt.dark?"#9fb0c0":"#667786",labelY=f.y+f.h+20;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" data-frame-aspect="${APP6D_FRAME_ASPECT[u.affiliation]||1.5}" aria-label="${esc(u.name)}"><g fill="none" stroke="${st.stroke}" stroke-width="2" color="${st.stroke}" stroke-linecap="round" stroke-linejoin="round">${frameShape(u.affiliation,f.x,f.y,f.w,f.h).replace("/>",` fill="${st.fill}"/>`)}${glyph(u.unitTypeId,g.x,g.y,g.w,g.h)}</g><text x="${width/2}" y="${Math.max(12,f.y-7)}" text-anchor="middle" fill="${st.stroke}" font-size="${Math.max(9,f.h*.22)}" font-weight="700">${esc(ec.symbol)}</text>${labels?`<text x="${width/2}" y="${labelY}" text-anchor="middle" fill="${label}" font-size="13" font-weight="700">${esc(u.name)}</text><text x="${width/2}" y="${labelY+16}" text-anchor="middle" fill="${muted}" font-size="10">${esc(unitType(u.unitTypeId).name)} · ${esc(ec.name)}</text>`:""}</svg>`}

function modal(title,fields,onConfirm){$("modalTitle").textContent=title;$("modalBody").innerHTML=`<div class="modal-form">${fields}</div>`;$("modal").hidden=false;$("modalConfirm").onclick=()=>{if(onConfirm()!==false)closeModal()}}
function closeModal(){$("modal").hidden=true}
function addUnit(parentId=null){
  modal("部隊を追加",`<label>部隊名<input id="mName" value="新規部隊"></label><label>エシュロン<select id="mEchelon">${selectOptions([...state.echelons].sort((a,b)=>a.rank-b.rank),"battalion",x=>`${x.symbol} ${x.name}`)}</select></label><label>兵科<select id="mType">${selectOptions(state.unitTypes,"infantry")}</select></label>`,()=>{const name=$("mName").value.trim();if(!name)return false;mutate(()=>{const sib=children(parentId);const id=uid("u");state.units.push({id,name,abbr:"",parentId,echelonId:$("mEchelon").value,unitTypeId:$("mType").value,affiliation:"friendly",sortOrder:sib.length?Math.max(...sib.map(x=>x.sortOrder))+1:1,personnel:0,equipment:[],notes:""});selectedId=id;collapsed.delete(parentId)});return true})
}
function deleteUnit(id){const u=unit(id),n=descendants(id).length;if(!u||!confirm(`「${u.name}」${n?`と配下${n}部隊`:""}を削除しますか？`))return;mutate(()=>{const remove=new Set([id,...descendants(id).map(x=>x.id)]);state.units=state.units.filter(x=>!remove.has(x.id));selectedId=state.units[0]?.id||null})}
function duplicateUnit(id){const src=unit(id);if(!src)return;mutate(()=>{const map=new Map();const copyNode=(old,parentId)=>{const nu=clone(old);nu.id=uid("u");nu.name=old===src?`${old.name}（複製）`:old.name;nu.parentId=parentId;nu.sortOrder=children(parentId).length+1;map.set(old.id,nu.id);state.units.push(nu);children(old.id).forEach(c=>copyNode(c,nu.id));return nu};selectedId=copyNode(src,src.parentId).id})}
function moveSibling(id,dir){const u=unit(id),s=children(u.parentId),i=s.findIndex(x=>x.id===id),j=i+dir;if(j<0||j>=s.length)return;mutate(()=>{const tmp=s[i].sortOrder;s[i].sortOrder=s[j].sortOrder;s[j].sortOrder=tmp;if(s[i].sortOrder===s[j].sortOrder){s.forEach((x,k)=>x.sortOrder=k+1)}})}

function renderCatalog(){const q=$("catalogSearch").value.toLowerCase(),limit=300;const matches=state.catalog.filter(x=>!q||`${x.name} ${x.category} ${x.specs}`.toLowerCase().includes(q)).sort((a,b)=>a.category.localeCompare(b.category,"ja")||a.name.localeCompare(b.name,"ja")),rows=matches.slice(0,limit);$("catalogCount").textContent=`全${state.catalog.length.toLocaleString()}件／該当${matches.length.toLocaleString()}件${matches.length>limit?`（先頭${limit}件を表示）`:""}`;$("catalogTable").innerHTML=`<table class="data-table"><thead><tr><th>区分</th><th>品目</th><th>生産国・諸元</th><th>配備先</th><th></th></tr></thead><tbody>${rows.map(x=>{const uses=state.units.filter(u=>(u.equipment||[]).some(a=>a.catalogId===x.id));return `<tr><td>${esc(x.category)}</td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.specs||"")}</td><td>${uses.length?`${uses.length}部隊 / ${uses.reduce((s,u)=>s+int(u.equipment.find(a=>a.catalogId===x.id)?.quantity),0)}`:"—"}</td><td><button data-catalog-edit="${x.id}">編集</button> <button class="danger" data-catalog-delete="${x.id}">削除</button></td></tr>`}).join("")}</tbody></table>`}
function editCatalog(id=null){const item=id?catalogItem(id):{name:"",category:state.categories[0]||"その他",specs:"",notes:""};modal(id?"品目を編集":"品目を追加",`<label>名称<input id="mCatName" value="${esc(item.name)}"></label><label>区分<input id="mCatCategory" list="categoryList" value="${esc(item.category)}"><datalist id="categoryList">${state.categories.map(x=>`<option value="${esc(x)}">`).join("")}</datalist></label><label>諸元<input id="mCatSpecs" value="${esc(item.specs)}"></label><label>備考<textarea id="mCatNotes">${esc(item.notes)}</textarea></label>`,()=>{const name=$("mCatName").value.trim(),category=$("mCatCategory").value.trim()||"その他";if(!name)return false;mutate(()=>{if(!state.categories.includes(category))state.categories.push(category);if(id)Object.assign(catalogItem(id),{name,category,specs:$("mCatSpecs").value,notes:$("mCatNotes").value});else state.catalog.push({id:uid("eq"),name,category,specs:$("mCatSpecs").value,notes:$("mCatNotes").value})});return true})}
function deleteCatalog(id){const x=catalogItem(id),uses=state.units.filter(u=>(u.equipment||[]).some(a=>a.catalogId===id));if(uses.length){alert(`「${x.name}」は ${uses.length} 部隊で使用中です。割当を削除してから再実行してください。\n\n${uses.map(u=>u.name).join("\n")}`);return}if(confirm(`「${x.name}」を削除しますか？`))mutate(()=>state.catalog=state.catalog.filter(c=>c.id!==id))}

function renderSettings(){$("settingsProjectName").value=state.meta.name;$("echelonTable").innerHTML=`<table class="data-table"><thead><tr><th>順位</th><th>名称</th><th>記号</th><th>区分</th><th></th></tr></thead><tbody>${[...state.echelons].sort((a,b)=>a.rank-b.rank).map(x=>`<tr><td>${x.rank}</td><td>${esc(x.name)}</td><td>${esc(x.symbol)}</td><td>${x.brigadeOrAbove?"旅団以上":"旅団未満"}</td><td><button data-echelon-edit="${x.id}">編集</button></td></tr>`).join("")}</tbody></table>`;$("unitTypeTable").innerHTML=`<table class="data-table"><thead><tr><th>名称</th><th>ID</th><th></th></tr></thead><tbody>${state.unitTypes.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.id)}</td><td><button data-type-edit="${x.id}">編集</button></td></tr>`).join("")}</tbody></table>`}
function editEchelon(id=null){const x=id?echelon(id):{name:"",symbol:"",rank:state.echelons.length+1,brigadeOrAbove:false};modal(id?"エシュロン編集":"エシュロン追加",`<label>名称<input id="mEName" value="${esc(x.name)}"></label><label>記号<input id="mESymbol" value="${esc(x.symbol)}"></label><label>順位<input id="mERank" type="number" min="1" value="${x.rank}"></label><label><input id="mEAbove" type="checkbox" ${x.brigadeOrAbove?"checked":""} style="width:auto"> 旅団以上（直接割当不可）</label>`,()=>{const name=$("mEName").value.trim();if(!name)return false;mutate(()=>{const data={name,symbol:$("mESymbol").value,rank:int($("mERank").value),brigadeOrAbove:$("mEAbove").checked};if(id)Object.assign(echelon(id),data);else state.echelons.push({id:uid("ech"),...data})});return true})}
function editUnitType(id=null){const x=id?unitType(id):{name:""};modal(id?"兵科編集":"兵科追加",`<label>名称<input id="mTName" value="${esc(x.name)}"></label><p>既定兵科以外は記号内に「?」を表示します。</p>`,()=>{const name=$("mTName").value.trim();if(!name)return false;mutate(()=>{if(id)unitType(id).name=name;else state.unitTypes.push({id:uid("type"),name})});return true})}

// JANUS phase-1 operational planning. COA generation is deliberately isolated so
// a future LLM adapter can replace the local deterministic generator without
// changing operation data, validation, snapshots or document generation.
const OPERATION_TASKS=["主攻","助攻","予備","火力支援","防空","ISR","電子戦","海上支援","航空支援","兵站","戦略予備"];
const JANUS_MAP={width:1536,height:1024,majorGridPx:45.77,minorGridPx:4.577,minorGridKm:100,version:2};
const OPERATION_FIELDS={opName:"name",opActor:"actor",opStart:"start",opEnd:"end",opEnemy:"enemy",opArea:"area",opIntent:"commanderIntent",opEndState:"endState",opObjectives:"objectives",opAvailableHours:"availableHours",opDistanceKm:"distanceKm",opSpeedKmh:"speedKmh",opAcceptableLosses:"acceptableLosses",opFailure:"failureConditions",opRoe:"roe",opPolitical:"politicalConstraints",opProhibited:"prohibitedWeapons",opFreeText:"freeText"};
const SHAPE_LABELS={objective:"作戦目標",route:"進出経路",area:"作戦区域",phase:"フェーズライン"};
const operationStatusLabel=s=>({draft:"下書き",checked:"検査済",submitted:"提出済"}[s]||"下書き");
function blankOperation(){const now=new Date(),end=new Date(now.getTime()+24*3600e3),local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);return{id:uid("op"),name:"新規作戦",status:"draft",actor:"",enemy:"",start:local(now),end:local(end),area:"",commanderIntent:"",endState:"",objectives:"",availableHours:24,distanceKm:0,speedKmh:0,acceptableLosses:"",failureConditions:"",roe:"",politicalConstraints:"",prohibitedWeapons:"",freeText:"",assignments:[],shapes:[],mapVersion:JANUS_MAP.version,coas:[],selectedCoaId:null,checks:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),submittedAt:null,snapshot:null}}
function normalizeOperation(op){Object.assign(op,{status:op.status||"draft",assignments:Array.isArray(op.assignments)?op.assignments:[],shapes:Array.isArray(op.shapes)?op.shapes:[],coas:Array.isArray(op.coas)?op.coas:[],checks:Array.isArray(op.checks)?op.checks:[],frozenOrder:op.frozenOrder||null});if(!op.mapVersion){for(const shape of op.shapes)for(const p of shape.points||[]){p.x=p.x*JANUS_MAP.width/1000;p.y=p.y*JANUS_MAP.height/600}op.mapVersion=JANUS_MAP.version}const mapped=operationRouteDistanceKm(op);if(mapped>0&&op.status!=="submitted")op.distanceKm=mapped;return op}
function currentOperation(){return (state.operations||[]).find(x=>x.id===selectedOperationId)}
function touchOperation(op){if(op.status!=="submitted")op.status="draft";op.checks=[];op.updatedAt=new Date().toISOString()}
function switchOperationPane(name){operationPane=name;document.querySelectorAll("[data-op-pane]").forEach(x=>x.classList.toggle("active",x.dataset.opPane===name));document.querySelectorAll(".operation-pane").forEach(x=>x.classList.toggle("active",x.id===`opPane${name[0].toUpperCase()+name.slice(1)}`))}
function renderOperations(){
  state.operations??=[];state.operations.forEach(normalizeOperation);if(selectedOperationId&&!state.operations.some(x=>x.id===selectedOperationId))selectedOperationId=null;if(!selectedOperationId&&state.operations.length)selectedOperationId=state.operations[0].id;
  $("operationList").innerHTML=state.operations.length?state.operations.map(op=>`<button data-operation-id="${op.id}" class="${op.id===selectedOperationId?"active":""}"><strong>${esc(op.name)}</strong><small>${operationStatusLabel(op.status)} · ${esc(op.actor||"主体未設定")}</small></button>`).join(""):`<p class="muted">作戦はまだない。</p>`;
  const judgeCurrentA=$("judgePlanA").value,judgeCurrentB=$("judgePlanB").value,judgeOptions=`<option value="">選択</option>`+state.operations.map(x=>`<option value="${x.id}">${esc(x.name)}［${operationStatusLabel(x.status)}］</option>`).join("");$("judgePlanA").innerHTML=judgeOptions;$("judgePlanB").innerHTML=judgeOptions;if(state.operations.some(x=>x.id===judgeCurrentA))$("judgePlanA").value=judgeCurrentA;if(state.operations.some(x=>x.id===judgeCurrentB))$("judgePlanB").value=judgeCurrentB;
  const op=currentOperation();$("operationEmpty").hidden=!!op;$("operationContent").hidden=!op;if(!op)return;
  $("operationTitle").textContent=op.name;$("operationStatus").textContent=operationStatusLabel(op.status);$("operationStatus").className=`operation-status ${op.status}`;
  Object.entries(OPERATION_FIELDS).forEach(([id,key])=>{$(id).value=op[key]??""});
  const locked=op.status==="submitted",mappedDistance=operationRouteDistanceKm(op);$("opDistanceKm").readOnly=locked||mappedDistance>0;$("opDistanceKm").title=mappedDistance>0?"作戦図の最長経路から自動算出":"経路未設定時は手入力可能";$("duplicateOperationBtn").disabled=false;$("validateOperationBtn").disabled=locked;$("submitOperationBtn").disabled=locked;$("submitOperationBtn").textContent=locked?"提出済":"提出・ロック";$("deleteOperationBtn").disabled=false;
  renderOperationForces(op);renderOperationMap(op);renderOperationCoas(op);renderOperationChecks(op);$("operationOrder").innerHTML=operationOrderHtml(op);switchOperationPane(operationPane);
  $("operationContent").querySelectorAll("input,textarea,select,button").forEach(el=>el.disabled=locked);document.querySelectorAll("[data-op-pane]").forEach(el=>el.disabled=false);["duplicateOperationBtn","deleteOperationBtn","printOperationBtn","exportOperationJsonBtn","mapZoomOutBtn","mapZoomResetBtn","mapZoomInBtn"].forEach(id=>$(id).disabled=false);
}
function renderOperationForces(op){
  const assigned=new Set(op.assignments.map(x=>x.unitId)),available=state.units.filter(x=>!assigned.has(x.id));$("opUnitPicker").innerHTML=available.length?selectOptions(available,available[0]?.id,x=>`${x.name}［${echelon(x.echelonId).name}］`):`<option value="">割当可能な部隊なし</option>`;
  if(!op.assignments.length){$("operationForces").innerHTML=`<p class="muted" style="padding:14px">ORBATから参加部隊を割り当てる。</p>`;return}
  $("operationForces").innerHTML=`<table class="data-table"><thead><tr><th>部隊</th><th>任務</th><th>人員</th><th>主要装備</th><th></th></tr></thead><tbody>${op.assignments.map(a=>{const u=unit(a.unitId),agg=u?aggregate(u.id):{personnel:0,equipment:{}},eq=Object.entries(agg.equipment).sort((x,y)=>y[1]-x[1]).slice(0,4).map(([id,q])=>`${catalogItem(id)?.name||id} ${q}`).join(" / ");return`<tr><td><strong>${esc(u?.name||`不明 (${a.unitId})`)}</strong><br><small>${u?esc(echelon(u.echelonId).name):"参照切れ"}</small></td><td><select class="operation-task" data-unit-id="${a.unitId}">${OPERATION_TASKS.map(t=>`<option ${t===a.task?"selected":""}>${t}</option>`).join("")}</select></td><td>${agg.personnel.toLocaleString()}</td><td>${esc(eq||"装備なし")}</td><td><button class="danger operation-unit-remove" data-unit-id="${a.unitId}">解除</button></td></tr>`}).join("")}</tbody></table>`
}
function shapeSvg(shape){const pts=(shape.points||[]).map(p=>`${p.x},${p.y}`).join(" "),p=shape.points?.[0]||{x:0,y:0};if(shape.type==="objective")return`<g><circle class="map-objective" cx="${p.x}" cy="${p.y}" r="10"/><path class="map-route" d="M${p.x-17} ${p.y}H${p.x+17}M${p.x} ${p.y-17}V${p.y+17}"/><text x="${p.x+17}" y="${p.y-15}">${esc(shape.name)}</text></g>`;if(shape.type==="area")return`<g><polygon class="map-area" points="${pts}"/><text x="${p.x+10}" y="${p.y-10}">${esc(shape.name)}</text></g>`;return`<g><polyline class="map-${shape.type}" points="${pts}"/><text x="${p.x+10}" y="${p.y-10}">${esc(shape.name)}</text></g>`}
function segmentDistanceKm(a,b){return Math.hypot(b.x-a.x,b.y-a.y)/JANUS_MAP.minorGridPx*JANUS_MAP.minorGridKm}
function shapeDistanceKm(shape){let km=0;for(let i=1;i<(shape.points||[]).length;i++)km+=segmentDistanceKm(shape.points[i-1],shape.points[i]);return Math.round(km)}
function operationRouteDistanceKm(op){const routes=(op.shapes||[]).filter(x=>x.type==="route").map(shapeDistanceKm);return routes.length?Math.max(...routes):0}
function snapMapPoint(point){const snap=v=>Math.round(v/JANUS_MAP.minorGridPx)*JANUS_MAP.minorGridPx;return{x:Math.max(0,Math.min(JANUS_MAP.width,snap(point.x))),y:Math.max(0,Math.min(JANUS_MAP.height,snap(point.y)))}}
function renderOperationMap(op){
  const draft=mapDraftPoints.length?`<polyline class="map-draft" points="${mapDraftPoints.map(p=>`${p.x},${p.y}`).join(" ")}"/>`:"",scale=`<g transform="translate(24 944)"><rect class="map-scale-bg" x="-10" y="-24" width="150" height="68" rx="7"/><line class="map-scale-line" x1="0" y1="10" x2="${JANUS_MAP.majorGridPx}" y2="10"/><line class="map-scale-line" x1="0" y1="2" x2="0" y2="18"/><line class="map-scale-line" x1="${JANUS_MAP.majorGridPx}" y1="2" x2="${JANUS_MAP.majorGridPx}" y2="18"/><text class="map-scale-text" x="0" y="-3">1,000 km</text></g>`;$("operationMapOverlay").innerHTML=`${op.shapes.map(shapeSvg).join("")}${draft}${scale}`;$("operationMap").style.width=`${Math.round(mapZoom*100)}%`;$("mapZoomResetBtn").textContent=`${Math.round(mapZoom*100)}%`;
  const routeKm=operationRouteDistanceKm(op),worldWidth=Math.round(JANUS_MAP.width/JANUS_MAP.minorGridPx*100),worldHeight=Math.round(JANUS_MAP.height/JANUS_MAP.minorGridPx*100);$("mapDistanceSummary").innerHTML=`<span>地図範囲 <strong>約${worldWidth.toLocaleString()} × ${worldHeight.toLocaleString()} km</strong></span><span>計画経路 <strong>${routeKm?`${routeKm.toLocaleString()} km`:"未設定"}</strong></span><span>換算 <strong>1小マス=100km</strong></span>`;
  $("operationShapes").innerHTML=op.shapes.length?`<div class="shape-list">${op.shapes.map(s=>`<span class="shape-chip">${SHAPE_LABELS[s.type]}：${esc(s.name)}${s.type==="route"?`（${shapeDistanceKm(s).toLocaleString()}km）`:""} <button data-shape-delete="${s.id}" aria-label="削除">×</button></span>`).join("")}</div>`:`<p class="muted" style="padding:0 14px 14px">目標・経路・区域を地図上に追加する。</p>`
}
function localCoaGenerator(op){const objective=op.objectives.trim()||op.endState.trim()||"設定した作戦目的",assigned=op.assignments.map(a=>({unitId:a.unitId,task:a.task})),names=assigned.map(a=>unit(a.unitId)?.name).filter(Boolean),force=names.length?names.join("、"):"割当戦力";return[
  {id:uid("coa"),type:"direct",title:"COA-A 直接型",summary:`${force}を集中し、${objective}へ最短経路で決定的効果を与える。`,phases:["ISRによる直前確認","主攻戦力の集中・同時打撃","目標確保と即時再編"],risks:["損耗が集中する","敵情と奇襲性への依存が大きい"],assignments:clone(assigned),generatedBy:"local-template-v1"},
  {id:uid("coa"),type:"shaping",title:"COA-B 形成型",summary:`ISR、防空制圧、陽動と補給遮断を先行し、敵の対応能力を低下させてから${objective}を達成する。`,phases:["ISR・電子戦・欺瞞による戦場形成","防空・指揮通信・兵站への限定打撃","主攻投入と目標確保"],risks:["所要時間が長い","形成作戦の成否が主攻開始条件となる"],assignments:clone(assigned),generatedBy:"local-template-v1"},
  {id:uid("coa"),type:"indirect",title:"COA-C 間接型",summary:`敵主力との正面衝突を避け、兵站・通信・海上交通・同盟関係への圧力によって${objective}を達成する。`,phases:["敵の依存関係と脆弱点を特定","分散した間接打撃・封鎖・情報作戦","交渉条件の形成と戦力温存"],risks:["効果発現が不確実","政治判断と長期的圧力に依存する"],assignments:clone(assigned),generatedBy:"local-template-v1"}
  ]}
function renderOperationCoas(op){$("coaCards").innerHTML=op.coas.length?op.coas.map(c=>`<article class="coa-card ${c.id===op.selectedCoaId?"selected":""}"><span class="eyebrow">${esc(c.type.toUpperCase())}</span><h3>${esc(c.title)}</h3><textarea class="coa-summary" data-coa-id="${c.id}" rows="5">${esc(c.summary)}</textarea><h4>フェーズ</h4><ol>${c.phases.map(x=>`<li>${esc(x)}</li>`).join("")}</ol><h4>主要リスク</h4><ul>${c.risks.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><button class="${c.id===op.selectedCoaId?"primary":""} select-coa" data-coa-id="${c.id}">${c.id===op.selectedCoaId?"採用中":"この案を採用"}</button></article>`).join(""):`<p class="muted" style="padding:0 14px 14px">基本情報と戦力を入力後、三つの行動方針を生成する。</p>`}
function operationChecks(op){const checks=[],add=(severity,message,code)=>checks.push({severity,message,code});for(const [value,label,code] of [[op.name,"作戦名","OP-NAME"],[op.actor,"作戦主体","OP-ACTOR"],[op.commanderIntent,"指揮官意図","OP-INTENT"],[op.endState,"最終状態","OP-ENDSTATE"],[op.objectives,"達成すべき目的","OP-OBJECTIVE"],[op.failureConditions,"失敗条件","OP-FAIL"]])if(!String(value||"").trim())add("error",`${label}が未設定である。`,code);
  const start=Date.parse(op.start),end=Date.parse(op.end),periodHours=(end-start)/36e5;if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)add("error","作戦期間が不正である。","TIME-PERIOD");else add("ok",`作戦期間は${periodHours.toFixed(1)}時間である。`,"TIME-PERIOD");
  const hours=Number(op.availableHours),mappedDistance=operationRouteDistanceKm(op),distance=mappedDistance||Number(op.distanceKm),speed=Number(op.speedKmh);if(mappedDistance)add("ok",`作戦図の最長経路を${mappedDistance.toLocaleString()}kmとして算出した。`,"MAP-DISTANCE");if(hours<=0)add("error","利用可能時間を設定する必要がある。","TIME-AVAILABLE");if(distance>0&&speed<=0)add("error","移動距離を検証するため平均速度が必要である。","MOVE-SPEED");if(distance>0&&speed>0){const required=distance/speed;if(required>hours)add("error",`移動所要${required.toFixed(1)}時間が利用可能時間${hours}時間を超える。`,"MOVE-RANGE");else add("ok",`移動所要${required.toFixed(1)}時間は利用可能時間内である。`,"MOVE-RANGE");if(Number.isFinite(periodHours)&&required>periodHours)add("error","移動所要時間が作戦期間を超える。","MOVE-PERIOD")}
  if(!op.assignments.length)add("error","作戦に参加するORBAT部隊が未割当である。","FORCE-NONE");const seen=new Set();for(const a of op.assignments){if(seen.has(a.unitId))add("error",`部隊ID ${a.unitId} が重複割当されている。`,"FORCE-DUP");seen.add(a.unitId);const u=unit(a.unitId);if(!u)add("error",`割当部隊 ${a.unitId} がORBATに存在しない。`,"FORCE-MISSING");else{const bad=Object.keys(aggregate(u.id).equipment).filter(id=>!catalogItem(id));if(bad.length)add("error",`${u.name}にカタログ参照切れが${bad.length}件ある。`,"EQUIPMENT-MISSING")}}
  for(let i=0;i<op.assignments.length;i++)for(let j=i+1;j<op.assignments.length;j++){const a=unit(op.assignments[i].unitId),b=unit(op.assignments[j].unitId);if(a&&b&&(descendants(a.id).some(x=>x.id===b.id)||descendants(b.id).some(x=>x.id===a.id)))add("warning",`${a.name}と${b.name}は親子関係にあり、戦力集計が重複しうる。`,"FORCE-OVERLAP")}
  for(const type of ["objective","route","area"])if(!op.shapes.some(x=>x.type===type))add("warning",`${SHAPE_LABELS[type]}が作戦図に未設定である。`,`MAP-${type.toUpperCase()}`);if(!op.coas.length)add("error","COAが生成されていない。","COA-NONE");if(op.coas.length&&!op.coas.some(x=>x.id===op.selectedCoaId))add("error","採用COAが選択されていない。","COA-SELECT");add("warning","兵器カタログに航続距離・射程の構造化属性が未整備のため、兵器個別の到達性検査は保留される。","CATALOG-PERFORMANCE");return checks}
function renderOperationChecks(op){const checks=op.checks||[];$("operationChecks").innerHTML=checks.length?`<div class="check-list">${checks.map(c=>`<div class="check-item ${c.severity}"><span class="check-severity">${c.severity==="error"?"エラー":c.severity==="warning"?"警告":"適合"}</span><span>${esc(c.message)} <small class="muted">${esc(c.code)}</small></span></div>`).join("")}</div>`:`<p class="muted" style="padding:14px">未検査。生成後・編集後・提出前に検査する。</p>`}
function rootOperationAssignments(op){const ids=new Set(op.assignments.map(x=>x.unitId));return op.assignments.filter(a=>{let u=unit(a.unitId);while(u?.parentId){if(ids.has(u.parentId))return false;u=unit(u.parentId)}return true})}
function operationAggregate(op){const out={personnel:0,equipment:{}};for(const a of rootOperationAssignments(op)){const agg=aggregate(a.unitId);out.personnel+=agg.personnel;for(const [id,q] of Object.entries(agg.equipment))out.equipment[id]=(out.equipment[id]||0)+q}return out}
function selectedCoa(op){return op.coas.find(x=>x.id===op.selectedCoaId)}
function operationOrderHtml(op){if(op.status==="submitted"&&op.frozenOrder)return op.frozenOrder;const coa=selectedCoa(op),force=operationAggregate(op),checks=op.checks||[],routeDistance=operationRouteDistanceKm(op),equipment=Object.entries(force.equipment).sort((a,b)=>b[1]-a[1]),mission=`${op.actor||"作戦主体"}は、${op.start||"開始時刻未定"}から${op.area||"作戦地域"}において、${op.objectives||"設定された目的"}を実施し、${op.endState||"所望の最終状態"}を達成する。`;return`<article><h1>${esc(op.name)}</h1><p class="order-meta">JANUS 作戦計画書 · ${operationStatusLabel(op.status)} · 更新 ${esc(op.updatedAt||"")}</p><h2>1. 情勢</h2><p><strong>作戦地域：</strong>${esc(op.area||"未設定")}<br><strong>敵情：</strong>${esc(op.enemy||"未設定")}<br><strong>友軍状況：</strong>${esc(op.actor||"未設定")}／割当${op.assignments.length}部隊<br><strong>情報上の不確実性：</strong>${esc(op.freeText||"別途情報見積を参照")}</p><h2>2. 任務</h2><p>${esc(mission)}</p><h2>3. 実行</h2><h3>指揮官意図</h3><p>${esc(op.commanderIntent||"未設定")}</p><h3>採用行動方針</h3><p><strong>${esc(coa?.title||"未選択")}</strong><br>${esc(coa?.summary||"COAを生成・選択すること。")}</p>${coa?`<h3>フェーズ</h3><ol>${coa.phases.map(x=>`<li>${esc(x)}</li>`).join("")}</ol>`:""}<h3>部隊任務</h3><table><thead><tr><th>部隊</th><th>階梯</th><th>任務</th></tr></thead><tbody>${op.assignments.map(a=>{const u=unit(a.unitId);return`<tr><td>${esc(u?.name||a.unitId)}</td><td>${esc(u?echelon(u.echelonId).name:"不明")}</td><td>${esc(a.task)}</td></tr>`}).join("")||`<tr><td colspan="3">未割当</td></tr>`}</tbody></table><p><strong>撤退・中止条件：</strong>${esc(op.failureConditions||"未設定")}<br><strong>作戦終了条件：</strong>${esc(op.endState||"未設定")}<br><strong>ROE：</strong>${esc(op.roe||"未設定")}</p><h2>4. 兵站</h2><p>重複する親子割当を除外した集計戦力：人員 ${force.personnel.toLocaleString()}名。計画移動距離：${(routeDistance||Number(op.distanceKm)||0).toLocaleString()}km${routeDistance?"（作戦図から算出）":""}。許容損耗：${esc(op.acceptableLosses||"未設定")}。</p><table><thead><tr><th>区分</th><th>品目</th><th>数量</th></tr></thead><tbody>${equipment.slice(0,30).map(([id,q])=>{const c=catalogItem(id);return`<tr><td>${esc(c?.category||"不明")}</td><td>${esc(c?.name||id)}</td><td>${q.toLocaleString()}</td></tr>`}).join("")||`<tr><td colspan="3">装備なし</td></tr>`}</tbody></table><h2>5. 指揮・通信</h2><p>作戦主体：${esc(op.actor||"未設定")}。指揮系統はORBAT上の上級・下級関係に従う。通信途絶時の権限移譲、作戦コード、識別規則は実施前に追記すること。</p><h2>付属書A 使用データ一覧</h2><p>ORBAT部隊 ${op.assignments.length}件、参照兵器 ${equipment.length}件、作戦図形 ${op.shapes.length}件。地図換算は1小マス100km、太線10マス1,000km。${op.snapshot?`情報スナップショット：${esc(op.snapshot.createdAt)}`:"提出時にスナップショットを確定する。"}</p><h2>付属書B 前提条件・検査結果</h2><ul>${checks.map(c=>`<li>[${c.severity.toUpperCase()}] ${esc(c.message)}</li>`).join("")||"<li>未検査</li>"}</ul><p><strong>政治的制約：</strong>${esc(op.politicalConstraints||"未設定")}<br><strong>使用禁止兵器：</strong>${esc(op.prohibitedWeapons||"未設定")}</p></article>`}
function createOperationSnapshot(op){const assigned=rootOperationAssignments(op),units=assigned.flatMap(a=>{const u=unit(a.unitId);return u?[u,...descendants(u.id)]:[]}),uniqueUnits=[...new Map(units.map(u=>[u.id,u])).values()],catalogIds=new Set(uniqueUnits.flatMap(u=>(u.equipment||[]).map(a=>a.catalogId)));return{createdAt:new Date().toISOString(),projectMeta:clone(state.meta),operation:clone({...op,snapshot:null}),units:clone(uniqueUnits),catalog:clone(state.catalog.filter(x=>catalogIds.has(x.id))),echelons:clone(state.echelons),unitTypes:clone(state.unitTypes)}}
function renderJudgeComparison(){const a=(state.operations||[]).find(x=>x.id===$("judgePlanA").value),b=(state.operations||[]).find(x=>x.id===$("judgePlanB").value);if(!a||!b){$("judgeComparison").innerHTML=`<div class="janus-card"><p class="muted" style="padding:14px">比較する2計画を選択する。</p></div>`;return}const card=op=>{const coa=selectedCoa(op),force=operationAggregate(op);return`<article class="janus-card judge-plan"><h2>${esc(op.name)}</h2><p><span class="operation-status ${op.status}">${operationStatusLabel(op.status)}</span></p><dl><dt>主体</dt><dd>${esc(op.actor||"未設定")}</dd><dt>敵対勢力</dt><dd>${esc(op.enemy||"未設定")}</dd><dt>期間</dt><dd>${esc(op.start)} ～ ${esc(op.end)}</dd><dt>地域</dt><dd>${esc(op.area||"未設定")}</dd><dt>COA</dt><dd>${esc(coa?.title||"未選択")}</dd><dt>戦力</dt><dd>${op.assignments.length}部隊／${force.personnel.toLocaleString()}名</dd><dt>検査</dt><dd>エラー ${(op.checks||[]).filter(x=>x.severity==="error").length}・警告 ${(op.checks||[]).filter(x=>x.severity==="warning").length}</dd></dl></article>`};const shared=a.assignments.filter(x=>b.assignments.some(y=>y.unitId===x.unitId)).map(x=>unit(x.unitId)?.name||x.unitId),overlap=Date.parse(a.start)<Date.parse(b.end)&&Date.parse(b.start)<Date.parse(a.end),sameArea=a.area&&b.area&&a.area===b.area;$("judgeComparison").innerHTML=card(a)+card(b)+`<div class="judge-collision"><h3>衝突候補</h3><p>${overlap?"作戦期間は重複する。":"作戦期間の重複はない。"}${sameArea?" 作戦地域は同一である。":""}</p><p>${shared.length?`同一部隊の二重使用：${esc(shared.join("、"))}`:"同一部隊の二重使用は検出されない。"}</p><p class="muted">JANUSは勝敗を即断しない。最終裁定は審判が行う。</p></div>`;switchOperationPane("judge")}

function populateChartRoots(){const current=$("chartRoot").value||selectedId;$("chartRoot").innerHTML=selectOptions(state.units,current,x=>`${x.name}［${echelon(x.echelonId).name}］`);if(!$("chartRoot").value&&state.units[0])$("chartRoot").value=state.units[0].id}
function chartNodes(rootId,maxDepth){const levels=[],walk=(id,depth)=>{if(depth>maxDepth)return;const u=unit(id);if(!u)return;(levels[depth]??=[]).push(u);children(id).forEach(c=>walk(c.id,depth+1))};walk(rootId,0);return levels}
function renderChart(){
  const rootId=$("chartRoot").value||selectedId||state.units[0]?.id;if(!rootId){$("chartCanvas").innerHTML="";return}const maxDepth=Number($("chartDepth").value),levels=chartNodes(rootId,maxDepth);const nodeW=170,nodeH=135,gapX=45,gapY=100,connectorEndGap=14,maxCount=Math.max(...levels.map(x=>x.length)),width=Math.max(900,maxCount*(nodeW+gapX)+80),height=Math.max(600,levels.length*(nodeH+gapY)+80);const pos=new Map();levels.forEach((list,d)=>{const total=list.length*nodeW+(list.length-1)*gapX,offset=(width-total)/2;list.forEach((u,i)=>pos.set(u.id,{x:offset+i*(nodeW+gapX),y:40+d*(nodeH+gapY)}))});let lines="";pos.forEach((p,id)=>children(id).forEach(c=>{const q=pos.get(c.id);if(q){const endY=q.y-connectorEndGap;lines+=`<path data-from="${id}" data-to="${c.id}" data-node-y="${q.y}" data-end-y="${endY}" d="M${p.x+nodeW/2} ${p.y+nodeH}V${p.y+nodeH+gapY*.42}H${q.x+nodeW/2}V${endY}"/>`}}));const nodes=[...pos].map(([id,p])=>{const u=unit(id),agg=aggregate(id),eq=Object.entries(agg.equipment).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([k,v])=>`${catalogItem(k)?.name||k} ${v}`).join(" / ");return `<g class="org-node" data-id="${id}" transform="translate(${p.x} ${p.y})">${unitSymbolSvg(u,{width:nodeW,height:100,labels:true,dark:false})}${$("showPersonnel").checked?`<text x="${nodeW/2}" y="115" text-anchor="middle" font-size="10" fill="#526171">人員 ${agg.personnel.toLocaleString()}</text>`:""}${$("showEquipment").checked?`<text x="${nodeW/2}" y="130" text-anchor="middle" font-size="9" fill="#526171">${esc(eq||"装備なし")}</text>`:""}</g>`}).join("");const svg=`<svg id="orgSvg" xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><rect width="100%" height="100%" fill="#ffffff"/><g fill="none" stroke="#7890a5" stroke-width="1.5">${lines}</g>${nodes}</svg>`;$("chartCanvas").className="chart-canvas";$("chartCanvas").innerHTML=svg;applyChartTransform();
}
function applyChartTransform(){$("chartCanvas").style.transform=`translate(${chartPan.x}px,${chartPan.y}px) scale(${chartZoom})`;$("zoomResetBtn").textContent=`${Math.round(chartZoom*100)}%`}
function exportSvg(){const svg=$("orgSvg");if(!svg)return;download(`${state.meta.name}-組織図.svg`,new Blob([`<?xml version="1.0" encoding="UTF-8"?>\n${svg.outerHTML}`],{type:"image/svg+xml"}))}
function exportPng(){const svg=$("orgSvg");if(!svg)return;const data=new XMLSerializer().serializeToString(svg),url=URL.createObjectURL(new Blob([data],{type:"image/svg+xml"})),img=new Image();img.onload=()=>{const canvas=document.createElement("canvas"),scale=2;canvas.width=svg.width.baseVal.value*scale;canvas.height=svg.height.baseVal.value*scale;const ctx=canvas.getContext("2d");ctx.scale(scale,scale);ctx.drawImage(img,0,0);canvas.toBlob(blob=>download(`${state.meta.name}-組織図.png`,blob),"image/png");URL.revokeObjectURL(url)};img.src=url}

function saveJson(){const violations=state.units.filter(u=>isAggregateOnly(u)&&((u.equipment||[]).length||u.personnel));if(violations.length&&!confirm(`${violations.length}件の旅団以上部隊に直接割当データがあります。警告を含む状態で保存しますか？`))return;state.meta.updatedAt=new Date().toISOString();download(`${state.meta.name}.orbat.json`,new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));dirty=false;updateHeader();toast("プロジェクトを保存しました")}
function exportRollup(kind="csv"){const rows=[["部隊","エシュロン","人員","兵器区分","品目","数量"]];state.units.forEach(u=>{const a=aggregate(u.id),entries=Object.entries(a.equipment);if(!entries.length)rows.push([u.name,echelon(u.echelonId).name,a.personnel,"","",0]);entries.forEach(([id,q])=>{const c=catalogItem(id);rows.push([u.name,echelon(u.echelonId).name,a.personnel,c?.category||"不明",c?.name||id,q])})});if(kind==="md"){const text=`| ${rows[0].join(" | ")} |\n|${rows[0].map(()=>"---").join("|")}|\n`+rows.slice(1).map(r=>`| ${r.join(" | ")} |`).join("\n");download(`${state.meta.name}-集計.md`,new Blob([text],{type:"text/markdown"}))}else{const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\r\n");download(`${state.meta.name}-集計.csv`,new Blob(["\ufeff"+csv],{type:"text/csv"}))}}

function bind(){
  $("operationMapBase").setAttribute("href",window.JANUS_MAP_DATA||"");
  document.querySelectorAll(".view-btn").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$("addRootBtn").onclick=()=>addUnit(null);$("undoBtn").onclick=undo;$("redoBtn").onclick=redo;$("saveBtn").onclick=saveJson;$("openBtn").onclick=()=>$("fileInput").click();$("newBtn").onclick=()=>{if(dirty&&!confirm("未保存の変更を破棄しますか？"))return;state=sampleProject();history=[];future=[];selectedId="u-bde";selectedOperationId=null;dirty=false;renderAll()};
  $("fileInput").onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());validateProject(data);const added=mergeBuiltInCatalog(data);state=data;state.operations??=[];state.operations.forEach(normalizeOperation);state.units.forEach(u=>{u.equipment??=[];u.affiliation??="friendly";u.sortOrder??=1});history=[];future=[];selectedId=state.units[0]?.id;selectedOperationId=state.operations[0]?.id||null;dirty=added>0;renderAll();toast(`プロジェクトを読み込みました${added?`（兵器${added}件を補完）`:""}`)}catch(err){alert(`読込に失敗しました: ${err.message}`)}e.target.value=""};
  $("unitTree").onclick=e=>{const b=e.target.closest("[data-action]");if(!b)return;const {action,id}=b.dataset;if(action==="select"){selectedId=id;renderAll()}if(action==="toggle"){collapsed.has(id)?collapsed.delete(id):collapsed.add(id);renderTree()}if(action==="add")addUnit(id);if(action==="up")moveSibling(id,-1);if(action==="down")moveSibling(id,1)};
  $("treeSearch").oninput=renderTree;$("expandAllBtn").onclick=()=>{collapsed.clear();renderTree()};$("collapseAllBtn").onclick=()=>{collapsed=new Set(state.units.map(x=>x.id));renderTree()};
  const fieldMap={unitName:"name",unitAbbr:"abbr",unitEchelon:"echelonId",unitType:"unitTypeId",unitAffiliation:"affiliation",unitNotes:"notes"};Object.entries(fieldMap).forEach(([id,key])=>$(id).onchange=()=>mutate(()=>unit(selectedId)[key]=$(id).value));
  $("unitParent").onchange=()=>mutate(()=>{const u=unit(selectedId);u.parentId=$("unitParent").value||null;u.sortOrder=children(u.parentId).length+1});$("unitPersonnel").onchange=()=>mutate(()=>unit(selectedId).personnel=int($("unitPersonnel").value));$("duplicateBtn").onclick=()=>duplicateUnit(selectedId);$("deleteUnitBtn").onclick=()=>deleteUnit(selectedId);$("openChartForUnit").onclick=()=>{$("chartRoot").value=selectedId;switchView("chart")};
  $("equipmentCategoryFilter").onchange=renderEquipmentPicker;$("addEquipmentBtn").onclick=()=>{const id=$("equipmentPicker").value,q=int($("equipmentQty").value);if(!id||!q)return;mutate(()=>{const list=unit(selectedId).equipment??=[];const old=list.find(x=>x.catalogId===id);old?old.quantity+=q:list.push({catalogId:id,quantity:q})})};$("directEquipment").onchange=e=>{if(!e.target.classList.contains("assignment-qty"))return;mutate(()=>{const a=unit(selectedId).equipment.find(x=>x.catalogId===e.target.dataset.id);a.quantity=int(e.target.value);unit(selectedId).equipment=unit(selectedId).equipment.filter(x=>x.quantity>0)})};$("directEquipment").onclick=e=>{const b=e.target.closest(".assignment-delete");if(b)mutate(()=>unit(selectedId).equipment=unit(selectedId).equipment.filter(x=>x.catalogId!==b.dataset.id))};
  $("addCatalogBtn").onclick=()=>editCatalog();$("catalogSearch").oninput=renderCatalog;$("catalogTable").onclick=e=>{const ed=e.target.closest("[data-catalog-edit]"),del=e.target.closest("[data-catalog-delete]");if(ed)editCatalog(ed.dataset.catalogEdit);if(del)deleteCatalog(del.dataset.catalogDelete)};$("importCsvBtn").onclick=()=>$("csvInput").click();$("csvInput").onchange=async e=>{const text=await e.target.files[0].text(),lines=text.replace(/^\ufeff/,"").split(/\r?\n/).filter(Boolean),head=lines.shift().split(",").map(x=>x.trim().toLowerCase());const parse=line=>line.match(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g).map(x=>x.replace(/,$/,"").replace(/^"|"$/g,"").replaceAll('""','"'));mutate(()=>lines.forEach(line=>{const v=parse(line),o=Object.fromEntries(head.map((h,i)=>[h,v[i]||""]));if(o.name){const category=o.category||"その他";if(!state.categories.includes(category))state.categories.push(category);state.catalog.push({id:uid("eq"),name:o.name,category,specs:o.specs||"",notes:o.notes||""})}}));e.target.value="";toast(`${lines.length}品目を取り込みました`)};
  $("newOperationBtn").onclick=()=>mutate(()=>{const op=blankOperation();state.operations??=[];state.operations.push(op);selectedOperationId=op.id;operationPane="brief";mapDraftPoints=[];mapZoom=1});
  $("operationList").onclick=e=>{const b=e.target.closest("[data-operation-id]");if(!b)return;selectedOperationId=b.dataset.operationId;operationPane="brief";mapDraftPoints=[];mapZoom=1;renderOperations()};
  document.querySelectorAll("[data-op-pane]").forEach(b=>b.onclick=()=>switchOperationPane(b.dataset.opPane));
  Object.entries(OPERATION_FIELDS).forEach(([id,key])=>$(id).onchange=()=>{const op=currentOperation();if(!op||op.status==="submitted")return;mutate(()=>{op[key]=["availableHours","distanceKm","speedKmh"].includes(key)?Math.max(0,Number($(id).value)||0):$(id).value;touchOperation(op)})});
  $("duplicateOperationBtn").onclick=()=>{const op=currentOperation();if(!op)return;mutate(()=>{const copy=clone(op);copy.id=uid("op");copy.name=`${op.name}（複製）`;copy.status="draft";copy.submittedAt=null;copy.snapshot=null;copy.frozenOrder=null;copy.checks=[];copy.createdAt=new Date().toISOString();copy.updatedAt=copy.createdAt;state.operations.push(copy);selectedOperationId=copy.id;operationPane="brief"})};
  $("deleteOperationBtn").onclick=()=>{const op=currentOperation();if(op&&confirm(`「${op.name}」を削除しますか？`))mutate(()=>{state.operations=state.operations.filter(x=>x.id!==op.id);selectedOperationId=state.operations[0]?.id||null})};
  $("addOperationUnitBtn").onclick=()=>{const op=currentOperation(),unitId=$("opUnitPicker").value;if(!op||op.status==="submitted"||!unitId)return;mutate(()=>{if(!op.assignments.some(x=>x.unitId===unitId))op.assignments.push({unitId,task:$("opTaskPicker").value});touchOperation(op)})};
  $("operationForces").onchange=e=>{if(!e.target.classList.contains("operation-task"))return;const op=currentOperation();if(!op||op.status==="submitted")return;mutate(()=>{const a=op.assignments.find(x=>x.unitId===e.target.dataset.unitId);if(a)a.task=e.target.value;touchOperation(op)})};
  $("operationForces").onclick=e=>{const b=e.target.closest(".operation-unit-remove"),op=currentOperation();if(!b||!op||op.status==="submitted")return;mutate(()=>{op.assignments=op.assignments.filter(x=>x.unitId!==b.dataset.unitId);touchOperation(op)})};
  $("operationMap").onclick=e=>{const op=currentOperation();if(!op||op.status==="submitted")return;const rect=$("operationMap").getBoundingClientRect(),raw={x:(e.clientX-rect.left)*JANUS_MAP.width/rect.width,y:(e.clientY-rect.top)*JANUS_MAP.height/rect.height},point=$("mapSnapGrid").checked?snapMapPoint(raw):{x:Math.round(raw.x),y:Math.round(raw.y)},type=$("mapShapeType").value,name=$("mapShapeName").value.trim()||`${SHAPE_LABELS[type]} ${op.shapes.length+1}`;if(type==="objective")mutate(()=>{op.shapes.push({id:uid("shape"),type,name,points:[point]});touchOperation(op)});else{mapDraftPoints.push(point);renderOperationMap(op)}};
  $("finishShapeBtn").onclick=()=>{const op=currentOperation(),type=$("mapShapeType").value,name=$("mapShapeName").value.trim()||`${SHAPE_LABELS[type]} ${op?.shapes.length+1}`,min=type==="area"?3:2;if(!op||op.status==="submitted"||type==="objective")return;if(mapDraftPoints.length<min){toast(`${SHAPE_LABELS[type]}には${min}点以上必要である`);return}const points=clone(mapDraftPoints);mapDraftPoints=[];mutate(()=>{op.shapes.push({id:uid("shape"),type,name,points});if(type==="route")op.distanceKm=operationRouteDistanceKm(op);touchOperation(op)})};
  $("cancelShapeBtn").onclick=()=>{mapDraftPoints=[];const op=currentOperation();if(op)renderOperationMap(op)};$("operationShapes").onclick=e=>{const b=e.target.closest("[data-shape-delete]"),op=currentOperation();if(!b||!op||op.status==="submitted")return;mutate(()=>{op.shapes=op.shapes.filter(x=>x.id!==b.dataset.shapeDelete);op.distanceKm=operationRouteDistanceKm(op);touchOperation(op)})};
  $("mapZoomOutBtn").onclick=()=>{mapZoom=Math.max(.5,mapZoom-.5);const op=currentOperation();if(op)renderOperationMap(op)};$("mapZoomInBtn").onclick=()=>{mapZoom=Math.min(8,mapZoom+.5);const op=currentOperation();if(op)renderOperationMap(op)};$("mapZoomResetBtn").onclick=()=>{mapZoom=1;const op=currentOperation();if(op)renderOperationMap(op)};
  $("generateCoaBtn").onclick=()=>{const op=currentOperation();if(!op||op.status==="submitted")return;mutate(()=>{op.coas=localCoaGenerator(op);op.selectedCoaId=op.coas[0].id;touchOperation(op)})};
  $("coaCards").onclick=e=>{const b=e.target.closest(".select-coa"),op=currentOperation();if(!b||!op||op.status==="submitted")return;mutate(()=>{op.selectedCoaId=b.dataset.coaId;touchOperation(op)})};$("coaCards").onchange=e=>{if(!e.target.classList.contains("coa-summary"))return;const op=currentOperation();if(!op||op.status==="submitted")return;mutate(()=>{const coa=op.coas.find(x=>x.id===e.target.dataset.coaId);if(coa)coa.summary=e.target.value;touchOperation(op)})};
  const validateCurrentOperation=()=>{const op=currentOperation();if(!op||op.status==="submitted")return;mutate(()=>{op.checks=operationChecks(op);op.status=op.checks.some(x=>x.severity==="error")?"draft":"checked";op.updatedAt=new Date().toISOString()});operationPane="coa";renderOperations()};$("validateOperationBtn").onclick=validateCurrentOperation;$("runChecksBtn").onclick=validateCurrentOperation;
  $("submitOperationBtn").onclick=()=>{const op=currentOperation();if(!op||op.status==="submitted")return;const checks=operationChecks(op),errors=checks.filter(x=>x.severity==="error");if(errors.length){mutate(()=>{op.checks=checks;op.status="draft"});operationPane="coa";renderOperations();toast(`提出不可：エラー${errors.length}件`);return}if(!confirm("提出後は編集できません。情報スナップショットを確定しますか？"))return;mutate(()=>{op.checks=checks;op.status="submitted";op.submittedAt=new Date().toISOString();op.updatedAt=op.submittedAt;op.snapshot=createOperationSnapshot(op);op.frozenOrder=operationOrderHtml(op)});toast("作戦計画を提出・ロックした")};
  $("exportOperationJsonBtn").onclick=()=>{const op=currentOperation();if(!op)return;const payload={schema:"janus-operation-1",exportedAt:new Date().toISOString(),operation:clone(op),snapshot:clone(op.snapshot||createOperationSnapshot(op))};download(`${op.name}.janus.json`,new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}))};
  $("printOperationBtn").onclick=()=>{const op=currentOperation();if(!op)return;const w=window.open("","_blank");if(!w){alert("印刷画面を開けませんでした。ポップアップを許可してください。");return}w.document.write(`<!doctype html><html lang="ja"><head><meta charset="utf-8"><title>${esc(op.name)}</title><style>body{font-family:"Yu Gothic",sans-serif;color:#111;max-width:900px;margin:32px auto;line-height:1.7}h1{text-align:center}h2{border-bottom:1px solid #555;margin-top:28px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #888;padding:6px;font-size:12px}.order-meta{text-align:center;color:#555}@page{size:A4;margin:16mm}</style></head><body>${operationOrderHtml(op)}</body></html>`);w.document.close();w.focus();w.print()};
  $("comparePlansBtn").onclick=renderJudgeComparison;
  $("settingsProjectName").onchange=()=>mutate(()=>state.meta.name=$("settingsProjectName").value.trim()||"名称未設定");$("addEchelonBtn").onclick=()=>editEchelon();$("addUnitTypeBtn").onclick=()=>editUnitType();$("echelonTable").onclick=e=>{const b=e.target.closest("[data-echelon-edit]");if(b)editEchelon(b.dataset.echelonEdit)};$("unitTypeTable").onclick=e=>{const b=e.target.closest("[data-type-edit]");if(b)editUnitType(b.dataset.typeEdit)};
  ["chartRoot","chartDepth","showPersonnel","showEquipment"].forEach(id=>$(id).onchange=renderChart);$("zoomInBtn").onclick=()=>{chartZoom=Math.min(2.5,chartZoom+.15);applyChartTransform()};$("zoomOutBtn").onclick=()=>{chartZoom=Math.max(.25,chartZoom-.15);applyChartTransform()};$("zoomResetBtn").onclick=()=>{chartZoom=1;chartPan={x:40,y:40};applyChartTransform()};$("exportCsvBtn").onclick=()=>exportRollup("csv");$("exportMdBtn").onclick=()=>exportRollup("md");$("exportSvgBtn").onclick=exportSvg;$("exportPngBtn").onclick=exportPng;$("chartCanvas").onclick=e=>{const n=e.target.closest(".org-node");if(n){selectedId=n.dataset.id;switchView("editor")}};
  $("chartViewport").onmousedown=e=>{panStart={x:e.clientX-chartPan.x,y:e.clientY-chartPan.y};$("chartViewport").classList.add("dragging")};window.addEventListener("mousemove",e=>{if(!panStart)return;chartPan={x:e.clientX-panStart.x,y:e.clientY-panStart.y};applyChartTransform()});window.addEventListener("mouseup",()=>{panStart=null;$("chartViewport").classList.remove("dragging")});$("chartViewport").addEventListener("wheel",e=>{e.preventDefault();chartZoom=Math.max(.25,Math.min(2.5,chartZoom+(e.deltaY<0?.1:-.1)));applyChartTransform()},{passive:false});
  $("modalClose").onclick=$("modalCancel").onclick=closeModal;$("modal").onclick=e=>{if(e.target===$("modal"))closeModal()};window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue=""}});window.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();saveJson()}});
}

bind();renderAll();
